Streamlined presets, better libs for programattic use
smartcontractkit/helmenv pull request #3
Opened 2021-11-18 13:46 UTC by jleeh

2021-11-18 19:46 UTC, kalverra requested changes
Just some naming questions/considerations.

2021-11-18 19:46 UTC, kalverra commented on environment/chart.go
> +	settings      *Chart
Make more sense to be named just `chart` instead of `settings` then?

2021-11-19 08:30 UTC, skudasov approved these changes
Great job!

2021-11-19 08:30 UTC, skudasov commented on cmd/cli/envcli.go
> -		Before: func(c *cli.Context) error {
Is there any other check that completely prevents a user to interact with an env when both `persistent` and `persistent_connection` are set to false?

2021-11-19 08:30 UTC, skudasov commented on cmd/cli/envcli.go
> +					if !e.Config.PersistentConnection {
I think it's better to forbid every possible interaction when using CLI (Debugging), so we can have only two modes:
1. CI run with `false/false` 
2. Local run where you setup env yourself and do that only once.
Local run will save some resources when debugging and make you write tests more carefully with, for example, UUIDs and cleanup, so if we decide to "batch" the tests later we don't need to "fix" them again.

2021-11-19 17:54 UTC, merged